#! /bin/sh

case "$1" in
	start)
		echo "Starting user led 1"
		start-stop-daemon -S -n daemon-user-led -a /usr/bin/daemon-user-led
		;;
	stop)
		echo "Stopping user led 1"
		start-stop-daemon -K -n daemon-user-led
		;;
	*)
		echo "Usage: $0 {start|stop}"
		exit 1
esac

exit 0